---
abstract: 'High-performance preforking PSGI/Plack web server'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  Test::Requires: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v0.9.1, Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.130870'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Starman
requires:
  Data::Dump: 0
  HTTP::Date: 0
  HTTP::Parser::XS: 0
  HTTP::Status: 0
  Net::Server: 0.91
  Plack: 0.9971
  Test::TCP: 1.11
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/miyagawa/Starman/issues
  homepage: https://github.com/miyagawa/Starman
  repository: https://github.com/miyagawa/Starman.git
version: 0.3007
